# Generated by Django 4.2.2 on 2023-07-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisements_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advertisements',
            new_name='Advertisement',
        ),
    ]
